<?php

namespace Database\Seeders;

use App\Models\Categoria;
use App\Models\Marca;
use App\Models\Producto;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RsaInventarioSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            $marcas = [
                'ACCESSPRO',
                'EPCOM',
                'HIKSEMI',
                'HIKVISION',
                'HILOOK',
                'PRECISION',
                'RUPTELA',
            ];

            foreach ($marcas as $nombre) {
                Marca::updateOrCreate(
                    ['nombre' => $nombre],
                    ['status' => 'activo']
                );
            }

            $categorias = [
                'ACCESO VEHICULAR',
                'ALARMAS',
                'ALMACENAMIENTO',
                'BATERIA',
                'CABLEADO',
                'CAJAS',
                'CAMARAS',
                'CERRADURAS',
                'DVR',
                'FERRETERIA',
                'FUENTES DE PODER',
                'FUNTES DE ALIMENTACIÓN',
                'GPS',
                'KITS',
                'REDES',
                'SIRENAS',
                'TRANSCEPTORES DE VIDEO',
                'VIDEO PORTEROS',
            ];

            foreach ($categorias as $nombre) {
                Categoria::updateOrCreate(
                    ['nombre' => $nombre, 'tipo' => 'PRODUCTO'],
                    ['status' => 'activo']
                );
            }

            $productos = [
                [
                    'marca' => 'ACCESSPRO',
                    'categoria' => 'ACCESO VEHICULAR',
                    'sku' => 'XBS-IR33',
                    'nombre' => 'XBS-IR33',
                    'descripcion' => 'Fotocelda Infrarroja (Transmisor Con Receptor) / Alcance de Hasta 10 metros / Uso en Barreras y Motores de Acceso Vehicular',
                    'stock' => 1,
                    'costo_lista' => 152.18,
                    'precio_venta' => 205.44,
                ],
                [
                    'marca' => 'ACCESSPRO',
                    'categoria' => 'ACCESO VEHICULAR',
                    'sku' => 'XB-DLP-1101',
                    'nombre' => 'XB-DLP-1101',
                    'descripcion' => 'Sensor de Masa de 1 Canal / Detección de Presencia o Pulso',
                    'stock' => 1,
                    'costo_lista' => 464.20,
                    'precio_venta' => 626.67,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'ALARMAS',
                    'sku' => 'DS-PDP18-EG2(P)',
                    'nombre' => 'DS-PDP18-EG2(P)',
                    'descripcion' => 'Detector PIR Cableado para Interior / Inmunidad a Mascotas / Rango de Detección de 18 mts / Angulo de 85.9° de Cobertura',
                    'stock' => 2,
                    'costo_lista' => 158.38,
                    'precio_venta' => 213.81,
                ],
                [
                    'marca' => 'HIKSEMI',
                    'categoria' => 'ALMACENAMIENTO',
                    'sku' => 'V300X/500GB',
                    'nombre' => 'V300X/500GB',
                    'descripcion' => 'SSD PARA VIDEOVIGILANCIA / Unidad de Estado Sólido / 500 GB / 2.5" / Alto Performance / Uso 24/7 / Compatible con DVR´s y NVR´s epcom / HiLook y HIKVISION (Seleccionados)',
                    'stock' => 0,
                    'costo_lista' => 691.07,
                    'precio_venta' => 932.94,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'BATERIA',
                    'sku' => 'LK5.512',
                    'nombre' => 'LK5.512',
                    'descripcion' => 'Batería 12 V / 5.5 Ah / UL / Vida útil promedio 5 años / Tecnología AGM / Para uso en equipo electrónico, Alarmas de Intrusión / Incendio/ Control de acceso / Video Vigilancia / Terminales F1 ( Incluye adaptador F',
                    'stock' => 2,
                    'costo_lista' => 177.72,
                    'precio_venta' => 239.92,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'BATERIA',
                    'sku' => 'LK712',
                    'nombre' => 'LK712',
                    'descripcion' => 'Batería 12 V / 7 Ah / UL / Tecnología AGM / Vida útil promedio 5 años / Uso en equipo electrónico, Alarmas de Intrusión / Incendio / Control de acceso / Video Vigilancia / Terminales F1 ( Incluye adaptador F2 )',
                    'stock' => 2,
                    'costo_lista' => 255.45,
                    'precio_venta' => 344.86,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'CABLEADO',
                    'sku' => 'LP-TM-042-UY',
                    'nombre' => 'LP-TM-042-UY',
                    'descripcion' => 'Conector de cables "UY" para cable calibre 24 / 100PZS',
                    'stock' => 0,
                    'costo_lista' => 120.00,
                    'precio_venta' => 162.00,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'CABLEADO',
                    'sku' => 'DS-1LN5E-S-100',
                    'nombre' => 'DS-1LN5E-S-100',
                    'descripcion' => 'obina de Cable UTP 100 Mts / Cat 5E (24 AWG) / Color Blanco / PVC (CM) / Uso en Interior / 100% Cobre / Aplicaciones de CCTV y Redes de Datos',
                    'stock' => 0,
                    'costo_lista' => 730.20,
                    'precio_venta' => 985.77,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'CAJAS',
                    'sku' => 'LP-WBX-100',
                    'nombre' => 'LP-WBX-100',
                    'descripcion' => 'Caja de Conexiones Impermeable IP65, 7 Entradas, Dimensiones 100 x 100 x 70 mm, para Instalaciones Industriales, Comerciales y Residenciales, Incluye Tornillería para su Instalación',
                    'stock' => 0,
                    'costo_lista' => 37.06,
                    'precio_venta' => 50.03,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'CAJAS',
                    'sku' => 'LP-WBX-150',
                    'nombre' => 'LP-WBX-150',
                    'descripcion' => 'Caja de Conexiones Impermeable IP65, 10 Entradas, Dimensiones 150 x 110 x 70 mm, para Instalaciones Industriales, Comerciales y Residenciales, Incluye Tornillería para su Instalación',
                    'stock' => 1,
                    'costo_lista' => 59.06,
                    'precio_venta' => 79.73,
                ],
                [
                    'marca' => 'PRECISION',
                    'categoria' => 'CAJAS',
                    'sku' => 'PST-0808-ER',
                    'nombre' => 'PST-0808-ER',
                    'descripcion' => 'Caja Derivación-Conexión de Plástico (89 X 89 X 50 mm) con 7 Glándulas de Goma. Para Instalaciones Comerciales, Residenciales e Industriales. Cerrado a Presión.',
                    'stock' => 5,
                    'costo_lista' => 36.42,
                    'precio_venta' => 49.17,
                ],
                [
                    'marca' => 'PRECISION',
                    'categoria' => 'CAJAS',
                    'sku' => 'PST-1010-ER',
                    'nombre' => 'PST-1010-ER',
                    'descripcion' => 'Caja Derivación-Conexión de Plástico (100 X 100 X 54 mm) con 7 Glándulas de Goma. Para Instalaciones Comerciales, Residenciales e Industriales. Incluye Tornillería para su Tapa.',
                    'stock' => 3,
                    'costo_lista' => 49.49,
                    'precio_venta' => 66.81,
                ],
                [
                    'marca' => 'PRECISION',
                    'categoria' => 'CAJAS',
                    'sku' => 'PST-1924-1ER',
                    'nombre' => 'PST-1924-1ER',
                    'descripcion' => 'Caja Derivación-Conexión de Plástico (190 X 240 X 165 mm) con 12 Glándulas de Goma. Para Instalaciones Comerciales, Residenciales e Industriales. Incluye Tornillería para su Tapa. Funciona También como Registro.',
                    'stock' => 3,
                    'costo_lista' => 129.74,
                    'precio_venta' => 175.15,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'CAMARAS',
                    'sku' => 'B8-TURBO-C/A',
                    'nombre' => 'B8-TURBO-C/A',
                    'descripcion' => '[ColorVu] Bala TURBOHD 2 Megapíxel (1080p) / Microfono Integrado / Imagen a color 24/7 / Lente 2.8 mm / METAL / Luz Blanca 20 mts / Exterior IP66 / TVI-AHD-CVI-CVBS / dWDR',
                    'stock' => 1,
                    'costo_lista' => 421.20,
                    'precio_venta' => 568.62,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'CAMARAS',
                    'sku' => 'DS-2CE5AH0T-VPIT3ZE(C)',
                    'nombre' => 'DS-2CE5AH0T-VPIT3ZE(C)',
                    'descripcion' => 'Domo TURBOHD 5 Megapixel / Lente Motorizado 2.7 - 13.5 mm / IR EXIR 40 mts / IK10 / IP67 / dWDR',
                    'stock' => 0,
                    'costo_lista' => 1285.99,
                    'precio_venta' => 1736.09,
                ],
                [
                    'marca' => 'HILOOK',
                    'categoria' => 'CAMARAS',
                    'sku' => 'THC-B120-MC',
                    'nombre' => 'THC-B120-MC',
                    'descripcion' => 'Bala TURBOHD 2 Megapíxeles (1080p) / Gran Angular 103º / Lente 2.8 mm / METAL / IR EXIR Inteligente 20 mts / Exterior IP66 / dWDR / TVI-AHD-CVI-CVBS',
                    'stock' => 2,
                    'costo_lista' => 239.71,
                    'precio_venta' => 323.61,
                ],
                [
                    'marca' => 'HILOOK',
                    'categoria' => 'CAMARAS',
                    'sku' => 'THC-T129-MS',
                    'nombre' => 'THC-T129-MS',
                    'descripcion' => '[ColorVu] Turret TURBOHD 1080p / Imagen a color 24/7 / Lente 2.8 mm / Micrófono Integrado / Luz Blanca 20 mts / IP66 / Metálica',
                    'stock' => 0,
                    'costo_lista' => 340.46,
                    'precio_venta' => 459.62,
                ],
                [
                    'marca' => 'HILOOK',
                    'categoria' => 'CAMARAS',
                    'sku' => 'THC-B120-MS',
                    'nombre' => 'THC-B120-MS',
                    'descripcion' => 'Bala TURBOHD 2 Megapíxel (1080p) / Gran Angular 106° / Lente 2.8 mm / Audio por Coaxitron / 30 mts IR EXIR / Exterior IP66 / 4 Tecnologías / dWDR',
                    'stock' => 4,
                    'costo_lista' => 358.63,
                    'precio_venta' => 484.15,
                ],
                [
                    'marca' => 'HILOOK',
                    'categoria' => 'CAMARAS',
                    'sku' => 'THC-B129-MS',
                    'nombre' => 'THC-B129-MS',
                    'descripcion' => '[ColorVu] Bala TURBOHD 2 Megapixel (1080p) / Imagen a Color 24/7 / Lente 2.8 mm / Microfono Integrado / Luz Blanca 20 mts / IP66 / Metálica',
                    'stock' => 8,
                    'costo_lista' => 368.36,
                    'precio_venta' => 497.29,
                ],
                [
                    'marca' => 'ACCESSPRO',
                    'categoria' => 'CERRADURAS',
                    'sku' => 'INTERPRO2',
                    'nombre' => 'INTERPRO2',
                    'descripcion' => 'Módulo para Esclusas para puertas Siempre Cerradas',
                    'stock' => 1,
                    'costo_lista' => 194.94,
                    'precio_venta' => 263.17,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'DVR',
                    'sku' => 'S04-TURBO-M1',
                    'nombre' => 'S04-TURBO-M1',
                    'descripcion' => 'DVR 4 Canales TurboHD + 1 Canal IP / 2 Megapixel (1080p) Lite / Acusense Lite (Evita Falsas Alarmas) / Audio por coaxitron / 1 Bahía de Disco Duro / H.265+ / Salida de Vídeo Full HD',
                    'stock' => 2,
                    'costo_lista' => 567.40,
                    'precio_venta' => 765.99,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'DVR',
                    'sku' => 'S08-TURBO-M1',
                    'nombre' => 'S08-TURBO-M1',
                    'descripcion' => 'DVR 8 Canales TurboHD + 2 Canales IP / 2 Megapixel (1080p) Lite / Acusense Lite (Evita Falsas Alarmas) / Audio por Coaxitron / 1 Bahía de Disco Duro / H.265+ / Salida de Vídeo Full HD',
                    'stock' => 2,
                    'costo_lista' => 687.72,
                    'precio_venta' => 928.42,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'DVR',
                    'sku' => 'S16-TURBO-M1',
                    'nombre' => 'S16-TURBO-M1',
                    'descripcion' => 'DVR 16 Canales TurboHD + 2 Canales IP / 2 Megapixel (1080p) Lite / Acusense Lite (Evita Falsas Alarmas) / Audio por Coaxitron / 1 Bahía de Disco Duro / H.265+ / Salida de Video Full HD',
                    'stock' => 1,
                    'costo_lista' => 1250.63,
                    'precio_venta' => 1688.35,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'DVR',
                    'sku' => 'DS-7104HGHI-K1(S)',
                    'nombre' => 'DS-7104HGHI-K1(S)',
                    'descripcion' => 'DVR 4 Canales TurboHD + 1 Canal IP / 2 Megapixel (1080p) Lite / Acusense Lite (Evita Falsas Alarmas) / Audio por Coaxitron / 1 Bahia de Disco Duro / H.265+ / Salida de Vídeo Full HD',
                    'stock' => 2,
                    'costo_lista' => 683.32,
                    'precio_venta' => 922.48,
                ],
                [
                    'marca' => 'HILOOK',
                    'categoria' => 'DVR',
                    'sku' => 'DVR-204G-M1(C)',
                    'nombre' => 'DVR-204G-M1(C)',
                    'descripcion' => 'DVR 4 Canales TurboHD + 1 Canal IP / 2 Megapíxel (1080p) Lite / Acusense Lite (Evita Falsas Alarmas) / Audio por Coaxitron / 1 Bahía de Disco Duro / H.265+ / Salida de Vídeo Full HD',
                    'stock' => 2,
                    'costo_lista' => 401.39,
                    'precio_venta' => 541.88,
                ],
                [
                    'marca' => 'HILOOK',
                    'categoria' => 'DVR',
                    'sku' => 'DVR-208G-M1(C)',
                    'nombre' => 'DVR-208G-M1(C)',
                    'descripcion' => 'DVR 8 Canales TurboHD + 2 Canales IP / 2 Megapíxel (1080P) Lite / Acusense Lite (Evita Falsas Alarmas) / Audio por Coaxitron / 1 Bahía de Disco Duro / H.265+ / 1 Canal de Audio / Salida de Vídeo Full HD',
                    'stock' => 2,
                    'costo_lista' => 505.34,
                    'precio_venta' => 682.21,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FERRETERIA',
                    'sku' => 'AE34162',
                    'nombre' => 'AE34162',
                    'descripcion' => 'Terminal tipo ojo / 1 / 4 " / 16 - 14 AWG / Azúl / Paquete de 25 piezas.',
                    'stock' => 2,
                    'costo_lista' => 16.88,
                    'precio_venta' => 22.79,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FERRETERIA',
                    'sku' => 'AE-205-62',
                    'nombre' => 'AE-205-62',
                    'descripcion' => 'Conector a tope aislado / 16- 14 AWG / Azúl / Paquete de 25 piezas',
                    'stock' => 2,
                    'costo_lista' => 14.38,
                    'precio_venta' => 19.41,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FERRETERIA',
                    'sku' => 'AE20570',
                    'nombre' => 'AE20570',
                    'descripcion' => 'Conector a tope aislado / 12-10 AWG / Amarillo / Paquete de 25 piezas.',
                    'stock' => 2,
                    'costo_lista' => 23.09,
                    'precio_venta' => 31.17,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FUENTES DE PODER',
                    'sku' => 'ACCORDL-1M',
                    'nombre' => 'ACCORDL-1M',
                    'descripcion' => 'Cable de Alimentación Eléctrica para 120-240 Vca / 1 Metro / 2 Clavijas tipo Americano / Conector en Forma tipo L',
                    'stock' => 5,
                    'costo_lista' => 46.06,
                    'precio_venta' => 62.18,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FUENTES DE PODER',
                    'sku' => 'PLDC1000',
                    'nombre' => 'PLDC1000',
                    'descripcion' => 'Adaptador de Pared de 12 Vcc @ 1 Amp Regulado / Uso en Interior / Múltiples Usos / Con cable de 95 cm',
                    'stock' => 5,
                    'costo_lista' => 58.93,
                    'precio_venta' => 79.56,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FUENTES DE PODER',
                    'sku' => 'PSD1202D',
                    'nombre' => 'PSD1202D',
                    'descripcion' => 'Adaptador de Pared de 12 Vcc Regulada / 2 Amp / Voltaje de Entrada de 100 - 240 VCA / Longitud del cable 96 cms.',
                    'stock' => 4,
                    'costo_lista' => 79.44,
                    'precio_venta' => 107.24,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FUENTES DE PODER',
                    'sku' => 'RT1640LS',
                    'nombre' => 'RT1640LS',
                    'descripcion' => 'Transformador 16 Vca 40 VA',
                    'stock' => 1,
                    'costo_lista' => 157.20,
                    'precio_venta' => 212.22,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FUENTES DE PODER',
                    'sku' => 'PS12DC4PBK',
                    'nombre' => 'PS12DC4PBK',
                    'descripcion' => 'Fuente de Alimentación con Gabinete de 4 Salidas de 11 - 15 Vcc / 5 Amper / Soporta Batería de Respaldo / Voltaje de Entrada: 96 - 264 Vca / Soporta Protección contra Sobrecorriente de Salida, Protección contra Cortocircuito',
                    'stock' => 1,
                    'costo_lista' => 412.86,
                    'precio_venta' => 557.36,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'FUENTES DE PODER',
                    'sku' => 'DS-2FA1225-C4/K',
                    'nombre' => 'DS-2FA1225-C4/K',
                    'descripcion' => 'Fuente de Poder Regulada 12 Vcc / 13.5 Vcc / 15 Vcc para 4 Cámaras / 4 Amp (1 Amp por Salida) / Voltaje de Entrada 90 - 130 VCA / Filtro de Ruido para Cámaras 4K / Modo para Largas Distancias',
                    'stock' => 3,
                    'costo_lista' => 373.20,
                    'precio_venta' => 503.82,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'FUENTES DE PODER',
                    'sku' => 'DS-2FA1205-C8/K',
                    'nombre' => 'DS-2FA1205-C8/K',
                    'descripcion' => 'Fuente de Poder Regulada 12 Vcc / 13.5 Vcc / 15 Vcc para 8 Cámaras / 8 Amperes (1 Amp por Salida) / Voltaje de Entrada 90 - 130 VCA / Filtro de Ruido para Cámaras 4K / Modo para Largas Distancias',
                    'stock' => 2,
                    'costo_lista' => 600.72,
                    'precio_venta' => 810.97,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'FUNTES DE ALIMENTACIÓN',
                    'sku' => 'XP18DC20HD',
                    'nombre' => 'XP18DC20HD',
                    'descripcion' => 'Fuente PREMIUM / 11-15 V / 18 canales / 20 A / Alta tecnología en seguridad / Doble ventilador / Hasta 1.8 Amperes por Salida / Filtro de ruido por canal / Diseño de alta gama.',
                    'stock' => 1,
                    'costo_lista' => 1113.35,
                    'precio_venta' => 1503.02,
                ],
                [
                    'marca' => 'ACCESSPRO',
                    'categoria' => 'GPS',
                    'sku' => 'PRORELAY',
                    'nombre' => 'PRORELAY',
                    'descripcion' => 'Módulo de Relevador',
                    'stock' => 2,
                    'costo_lista' => 42.36,
                    'precio_venta' => 57.19,
                ],
                [
                    'marca' => 'RUPTELA',
                    'categoria' => 'GPS',
                    'sku' => 'ECO5 LITE',
                    'nombre' => 'ECO5 LITE',
                    'descripcion' => 'Rastreador Vehicular y Monitoreo de Flota / BLE 5.0 y GNSS / LTE CAT1 y LTE-M con Respaldo 2G / GNSS U-blox / MiKado IP54 / -20 °C a +40 °C / Acelerómetro de 3 Ejes / Suministro 9-32 V / Batería Interna',
                    'stock' => 3,
                    'costo_lista' => 910.73,
                    'precio_venta' => 1229.49,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'KITS',
                    'sku' => 'HIK5MPSLQ-KIT(B)',
                    'nombre' => 'HIK5MPSLQ-KIT(B)',
                    'descripcion' => '(MICRÓFONO INTEGRADO) KIT TURBOHD 5 Megapixel / DVR 4 Canales / 4 Cámaras Bala con Micrófono Integrado (exterior 2.8 mm) / Fuente de Poder / Accesorios de Instalación',
                    'stock' => 1,
                    'costo_lista' => 3068.43,
                    'precio_venta' => 4142.38,
                ],
                [
                    'marca' => 'HILOOK',
                    'categoria' => 'KITS',
                    'sku' => 'HL24LQKITS-M',
                    'nombre' => 'HL24LQKITS-M',
                    'descripcion' => 'KIT TurboHD 1080p / DVR 4 canales / 4 Cámaras Bala de Metal / H.265+ / 1 Fuente de Poder Profesional / Accesorios de Instalación',
                    'stock' => 0,
                    'costo_lista' => 1420.20,
                    'precio_venta' => 1917.27,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'REDES',
                    'sku' => 'DS-3E1505P-EI/M',
                    'nombre' => 'DS-3E1505P-EI/M',
                    'descripcion' => 'Switch Gigabit PoE+ / Monitoreable / 4 Puertos 1000 Mbps PoE+ / 1 Puerto 1000 Mbps Uplink / Configuración Nube Hik-PartnerPro / Modo Extendido hasta 300 Metros / 45 Watts',
                    'stock' => 1,
                    'costo_lista' => 586.04,
                    'precio_venta' => 791.15,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'SIRENAS',
                    'sku' => 'IMP-30-V3',
                    'nombre' => 'IMP-30-V3',
                    'descripcion' => 'Gabinete para Resguardo de Sirena de 30 W (SF581A o SF581L No incluida), Preparación para Tamper (No incluido).',
                    'stock' => 2,
                    'costo_lista' => 277.18,
                    'precio_venta' => 374.19,
                ],
                [
                    'marca' => 'EPCOM',
                    'categoria' => 'TRANSCEPTORES DE VIDEO',
                    'sku' => 'TT-101-F-TURBO',
                    'nombre' => 'TT-101-F-TURBO',
                    'descripcion' => 'Kit de Transceptores (Baluns) con Terminal PUSH SUPERIOR, Resolución 4K , Cable flexible COAXIAL Blindado / COAXITRON / AUDIO POR COAXITRON / Menu OSD /Conector 100% COBRE / protección TVS, Calidad PREMIUM',
                    'stock' => 21,
                    'costo_lista' => 45.26,
                    'precio_venta' => 61.10,
                ],
                [
                    'marca' => 'HIKVISION',
                    'categoria' => 'VIDEO PORTEROS',
                    'sku' => 'DS-KIS302-P',
                    'nombre' => 'DS-KIS302-P',
                    'descripcion' => 'Kit de Videoportero Híbrido de Plastico / IP a 4 Hilos con Función de Llamada a App Hik-Connect / Monitor se Conecta a Internet por Cable o WiFi y por 4 Hilos al Frente de Calle / Expandible a Mas Equipos',
                    'stock' => 2,
                    'costo_lista' => 2154.90,
                    'precio_venta' => 2909.12,
                ],
            ];

            foreach ($productos as $item) {
                $marca = Marca::where('nombre', $item['marca'])->first();

                $categoria = Categoria::where('nombre', $item['categoria'])
                    ->where('tipo', 'PRODUCTO')
                    ->first();

                Producto::updateOrCreate(
                    ['sku' => $item['sku']],
                    [
                        'marca_id' => $marca?->id,
                        'categoria_id' => $categoria?->id,
                        'nombre' => $item['nombre'],
                        'descripcion' => $item['descripcion'],
                        'stock' => $item['stock'],
                        'costo_lista' => $item['costo_lista'],
                        'precio_venta' => $item['precio_venta'],
                        'status' => 'activo',
                        'created_by' => null,
                        'updated_by' => null,
                        'deleted_by' => null,
                    ]
                );
            }
        });
    }
}